# Generated by Django 3.0.5 on 2020-04-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_auto_20200411_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip',
        ),
    ]
