# Generated by Django 3.0.5 on 2020-04-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isVisibilityAll',
            field=models.BooleanField(default=True),
        ),
    ]
