# Generated by Django 3.0.5 on 2020-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialWebApp', '0002_post_isvisibilityall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='isVisibilityAll',
            field=models.CharField(default='True', max_length=5),
        ),
    ]
